dist: trusty
sudo: required
services:
- docker
language: go
go:
- '1.12.6'
git:
  depth: 1
install:
- sudo apt-get install make
script:
- make all
matrix:
  fast_finish: true
  allow_failures:
  - go: tip

