apiVersion: v1
data:
  admin_password: {{ .Values.adminPassword | b64enc }}
  credentials_py:  {{ include "awx-helm.credentials_py" . | b64enc }}
  environment_sh: {{ include "awx-helm.environment_sh" . | b64enc }}
  pg_password: {{ .Values.postgresql.postgresqlPassword | b64enc }}
  rabbitmq_erlang_cookie: {{ .Values.rabbitmq.rabbitmqErlangCookie | b64enc}}
  rabbitmq_password: {{ .Values.rabbitmq.rabbitmqPassword | b64enc }}
  secret_key: {{ .Values.secretKey | b64enc }}
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
